// Generated by CoffeeScript 1.9.1
(function() {
  angular.element(document).ready(function() {
    var currentUser, permission, storage;
    if (!$.cookie('infoarchives_current_user')) {
      storage = window.localStorage;
      storage.setItem("before_login_url", window.location.href);
      window.location.href = window.hsConfig.loginUrl;
      return;
    }
    currentUser = JSON.parse($.cookie('infoarchives_current_user'));
    permission = {};
    return $.get(window.hsConfig.baseUrl + '/user/permit', {
      accessToken: currentUser.accessToken
    }, function(data, status) {
      if (data.code === '0') {
        $.cookie('infoarchives_current_user', null);
        storage = window.localStorage;
        storage.setItem("before_login_url", window.location.href);
        window.location.href = window.hsConfig.loginUrl;
        return;
      }
      permission = data.data;
      return $.get(window.hsConfig.adminBaseUrl + '/user/permit', {
        accessToken: currentUser.accessToken
      }, function(data, status) {
        permission.logManage = data.data.logManage;
        permission.userManage = data.data.userManage;
        if (!permission.statistics && !permission.connectMap) {
          permission.status = false;
        } else {
          permission.status = true;
        }
        if (!permission.batch && !permission.dataBase) {
          permission.dataManage = false;
        } else {
          permission.dataManage = true;
        }
        if (!permission.serviceWatch && !permission.userManage && !permission.logManage) {
          permission.other = false;
        } else {
          permission.other = true;
        }
        $.cookie('infoarchives_user_permission', JSON.stringify(permission));
        return angular.bootstrap(document, ['myApp']);
      });
    });
  });

}).call(this);

//# sourceMappingURL=app.ready.js.map
