// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").service("dataBaseService", [
    '$log', '$q', '$timeout', 'Restangular', 'hsAPI', 'MockRestangular', 'hsTpl', 'hsAuth', 'mdToastService', 'uuid', function($log, $q, $timeout, Restangular, hsAPI, MockRestangular, hsTpl, hsAuth, mdToastService, uuid) {
      var dataBase, getDataList, getGridData, getTreeData, recordList;
      getDataList = function() {
        var deferred, res;
        deferred = $q.defer();
        res = {};
        res.data = [
          {
            displayName: 'db_行政审批系统',
            objectId: '1'
          }, {
            displayName: 'db_医学出生证明系统',
            objectId: '2'
          }, {
            displayName: 'db_婚姻登记系统',
            objectId: '3'
          }
        ];
        deferred.resolve(res);
        return deferred.promise;
      };
      getGridData = function(info) {
        var deferred;
        deferred = $q.defer();
        info.accessUser = hsAuth.getAccessKey();
        info.accessToken = hsAuth.getAccessToken();
        Restangular.one(hsAPI['getRecordList']).get(info).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      dataBase = [
        {
          name: 'SipId',
          headerCellFilter: 'translate',
          displayName: '批次号',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'dataPath',
          headerCellFilter: 'translate',
          displayName: '数据位置',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'dataSize',
          headerCellFilter: 'translate',
          displayName: '数据大小',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'startData',
          headerCellFilter: 'translate',
          displayName: '开始事件',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }
      ];
      getTreeData = function(units, shixiangnums) {
        var data, i, x;
        units = parseInt(Math.random() * 25 + 5, 10);
        data = {
          "name": "Root",
          "objectId": uuid.v4(),
          "children": []
        };
        i = 0;
        while (i < units) {
          data.children.push({
            name: '单位' + i,
            objectId: uuid.v4(),
            type: 'unit',
            children: []
          });
          x = 0;
          shixiangnums = parseInt(Math.random() * 10, 10);
          while (x < shixiangnums) {
            data.children[i].children.push({
              name: '单位' + i + '事项' + x,
              type: 'items',
              children: [],
              objectId: uuid.v4()
            });
            x++;
          }
          i++;
        }
        return data;
      };
      recordList = [
        {
          name: 'archivalId',
          headerCellFilter: 'translate',
          displayName: '档号',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'batchCode',
          headerCellFilter: 'translate',
          displayName: '批次号',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'businessCode',
          headerCellFilter: 'translate',
          displayName: '业务流水号',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'name',
          headerCellFilter: 'translate',
          displayName: '事项名称',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'recordCode',
          headerCellFilter: 'translate',
          displayName: '证照编号',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'createDate',
          headerCellFilter: 'translate',
          displayName: '创建时间',
          minWidth: 50,
          cellTemplate: 'modules/dataBase/template/ui-grid-template/grid-recordList-createDate.html'
        }, {
          name: 'modifyDate',
          headerCellFilter: 'translate',
          displayName: '修改时间',
          minWidth: 50,
          cellTemplate: 'modules/dataBase/template/ui-grid-template/grid-recordList-modifyDate.html'
        }
      ];
      this.recordList = recordList;
      this.getTreeData = getTreeData;
      this.dataBase = dataBase;
      this.getGridData = getGridData;
      this.getDataList = getDataList;
    }
  ]);

}).call(this);

//# sourceMappingURL=dataBase.service.js.map
