// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").factory('permissions', [
    '$rootScope', 'hsAuth', function($rootScope, hsAuth) {
      return {
        hasPermission: function(permission) {
          var permissionLists;
          permission = permission.trim();
          permissionLists = hsAuth.getPermission();
          return permissionLists[permission];
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=permissions.factory.js.map
