// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").service("dataModuleService", [
    '$log', '$q', '$timeout', '$mdToast', 'MockRestangular', 'hsAPI', 'mdToastService', 'hsAuth', 'Restangular', '$http', function($log, $q, $timeout, $mdToast, MockRestangular, hsAPI, mdToastService, hsAuth, Restangular, $http) {
      var createModule, editModule, getModuleInfo, getModuleVersionList, updateVersion;
      getModuleVersionList = function(id) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['getModuleVersionList']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          projectId: id
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      createModule = function(containers, attrRules, id) {
        var deferred, obj;
        deferred = $q.defer();
        obj = {
          "containers": containers,
          "attrRules": attrRules,
          "template": {
            projectId: id
          }
        };
        MockRestangular.all(hsAPI['createModule'] + '?accessUser=' + hsAuth.getAccessKey() + '&accessToken=' + hsAuth.getAccessToken()).post(obj).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      updateVersion = function(containers, attrRules, template) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.all(hsAPI['updateVersion'] + '?accessUser=' + hsAuth.getAccessKey() + '&accessToken=' + hsAuth.getAccessToken()).post({
          "containers": containers,
          "attrRules": attrRules,
          "template": template
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      editModule = function(containers, attrRules, template) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['editModule']).post({
          "containers": containers,
          "attrRules": attrRules,
          "template": template
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getModuleInfo = function(id) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['getModuleInfo']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          objectId: id
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      this.getModuleInfo = getModuleInfo;
      this.editModule = editModule;
      this.updateVersion = updateVersion;
      this.createModule = createModule;
      this.getModuleVersionList = getModuleVersionList;
    }
  ]);

}).call(this);

//# sourceMappingURL=dataModule.service.js.map
