// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").service("userManageService", ['$log', '$q', '$timeout', '$mdToast', function($log, $q, $timeout, $mdToast) {}]);

}).call(this);

//# sourceMappingURL=userManage.service.js.map
