// Generated by CoffeeScript 1.9.1
(function() {
  angular.module("myApp").factory('hsAuth', [
    '$log', 'Cookies', function($log, Cookies) {
      var _permission, _user, getAccessKey, getAccessToken, getPermission, getUser, getUserId, isLogin, removeUser, service, setUser;
      _user = Cookies.getJSON('infoarchives_current_user');
      _permission = Cookies.getJSON('infoarchives_user_permission');
      isLogin = function() {
        if (_user) {
          return true;
        } else {
          return false;
        }
      };
      getAccessKey = function() {
        return _user.accessKey;
      };
      getAccessToken = function() {
        return _user.accessToken;
      };
      getUserId = function() {
        return _user.id;
      };
      getUser = function() {
        return Cookies.getJSON('infoarchives_current_user');
      };
      setUser = function(user, para) {
        para = para || {};
        Cookies.set('infoarchives_current_user', user, para);
        return _user = Cookies.getJSON('infoarchives_current_user');
      };
      removeUser = function() {
        return Cookies.remove('infoarchives_current_user');
      };
      getPermission = function() {
        return _permission;
      };
      return service = {
        getPermission: getPermission,
        getUserId: getUserId,
        setUser: setUser,
        isLogin: isLogin,
        getAccessKey: getAccessKey,
        getAccessToken: getAccessToken,
        getUser: getUser,
        removeUser: removeUser
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=commonAuth.js.map
