// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").service("ruleSetService", [
    '$log', '$q', '$timeout', '$mdToast', 'MockRestangular', 'hsAPI', 'mdToastService', 'hsAuth', 'Restangular', function($log, $q, $timeout, $mdToast, MockRestangular, hsAPI, mdToastService, hsAuth, Restangular) {
      var createRule, getProperty, getRetentionPeriodId, getRetentionPeriodList, getRule, saveRetentionPeriod, saveRule;
      getRule = function(id) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['getRule']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          objectId: id
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getProperty = function(id) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['getProperty']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          projectId: id
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      saveRule = function(fileds, codingPolicy) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['saveRule']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          data: {
            fileds: fileds,
            codingPolicy: codingPolicy
          }
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      createRule = function(fileds, projectId) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['createRule']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          data: {
            fileds: fileds
          },
          projectId: projectId
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getRetentionPeriodId = function(id) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['getRetentionPeriodId']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          projectId: id
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getRetentionPeriodList = function() {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['getRetentionPeriodList']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken()
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      saveRetentionPeriod = function(retentionPeriodId, projectId) {
        var deferred;
        deferred = $q.defer();
        MockRestangular.one(hsAPI['saveRetentionPeriod']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          projectId: projectId,
          retentionPeriodId: retentionPeriodId
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      this.saveRetentionPeriod = saveRetentionPeriod;
      this.getRetentionPeriodId = getRetentionPeriodId;
      this.getRetentionPeriodList = getRetentionPeriodList;
      this.createRule = createRule;
      this.saveRule = saveRule;
      this.getProperty = getProperty;
      this.getRule = getRule;
    }
  ]);

}).call(this);

//# sourceMappingURL=ruleSet.service.js.map
