// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").service("batchService", [
    '$log', '$q', '$timeout', '$mdToast', 'hsAuth', 'Restangular', 'hsAPI', 'hsTpl', 'mdToastService', 'MockRestangular', 'commonMethodSerivce', '$state', function($log, $q, $timeout, $mdToast, hsAuth, Restangular, hsAPI, hsTpl, mdToastService, MockRestangular, commonMethodSerivce, $state) {
      var batch, batchErrorList, checkForceSwitch, deleteBatch, exportList, forceSwitch, getDetailInfo, getErrorGridData, getErrorList, getGridData, getPackageList, packageList;
      getGridData = function(parameter) {
        var columns, deferred, info, orders;
        info = angular.copy(parameter);
        deferred = $q.defer();
        if (parameter.sortField && parameter.sortWay) {
          orders = [
            {
              column: parameter.sortField,
              direction: parameter.sortWay
            }
          ];
        } else {
          orders = [];
        }
        columns = [];
        if (info.projectId) {
          columns.push(commonMethodSerivce.initColumn('projectId', 'EQUAL', 'string', info.projectId));
        }
        if (parameter.start_date) {
          columns.push(commonMethodSerivce.initColumn('packageAiuStartDate', 'GREATER_THAN', 'date', info.start_date));
        }
        if (parameter.end_date) {
          columns.push(commonMethodSerivce.initColumn('packageAiuStartDate', 'LESS_THAN', 'date', info.end_date));
        }
        if (parameter.exception_handle_behavior && parameter.exception_handle_behavior.length > 0) {
          columns.push(commonMethodSerivce.initColumn('exceptionHandleBehavior', 'IN', 'int', info.exception_handle_behavior.join(',')));
        }
        if (parameter.batch_status && parameter.batch_status !== 'all') {
          columns.push(commonMethodSerivce.initColumn('batchStatus', 'IN', 'int', info.batch_status));
        }
        Restangular.all(hsAPI['getBatchList'] + '?accessUser=' + hsAuth.getAccessKey() + '&accessToken=' + hsAuth.getAccessToken()).post({
          columns: columns,
          orders: orders,
          page: parameter.currentPage,
          length: parameter.pageSize
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      exportList = function(parameter) {
        var columns, deferred, info;
        info = angular.copy(parameter);
        deferred = $q.defer();
        columns = [];
        if (info.projectId) {
          columns.push(commonMethodSerivce.initColumn('projectId', 'EQUAL', 'string', info.projectId));
        }
        if (parameter.start_date) {
          columns.push(commonMethodSerivce.initColumn('packageAiuStartDate', 'GREATER_THAN', 'date', info.start_date));
        }
        if (parameter.end_date) {
          columns.push(commonMethodSerivce.initColumn('packageAipEndDate', 'LESS_THAN', 'date', info.end_date));
        }
        if (parameter.exception_handle_behavior && parameter.exception_handle_behavior.length > 0) {
          columns.push(commonMethodSerivce.initColumn('exceptionHandleBehavior', 'IN', 'int', info.exception_handle_behavior.join(',')));
        }
        if (parameter.batch_status && parameter.batch_status !== 'all') {
          columns.push(commonMethodSerivce.initColumn('batchStatus', 'IN', 'int', info.batch_status));
        }
        Restangular.all(hsAPI['exportBatchList'] + '?accessUser=' + hsAuth.getAccessKey() + '&accessToken=' + hsAuth.getAccessToken()).post({
          columns: columns
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getErrorList = function(id) {
        var deferred;
        deferred = $q.defer();
        Restangular.one(hsAPI['getErrorList']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          batchId: id
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      deleteBatch = function(ids) {
        var deferred;
        deferred = $q.defer();
        Restangular.one(hsAPI['deleteBatch']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          ids: ids
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getDetailInfo = function(id) {
        var deferred;
        deferred = $q.defer();
        Restangular.one(hsAPI['getBatchDetail']).withHttpConfig({
          ignoreLoadingBar: true
        }).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          id: id
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getErrorGridData = function(parameter) {
        var deferred;
        deferred = $q.defer();
        Restangular.one(hsAPI['getErrorGridData']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          exceptionRecordId: parameter.objectId,
          currentPage: parameter.currentPage,
          pageSize: parameter.pageSize
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      getPackageList = function(parameter) {
        var deferred;
        deferred = $q.defer();
        Restangular.one(hsAPI['getPackageList']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          batchId: parameter.batchId,
          currentPage: parameter.currentPage,
          pageSize: parameter.pageSize
        }).then(function(res) {
          if (res.code === '1') {
            return deferred.resolve(res.data);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      checkForceSwitch = function(ids) {
        var deferred;
        deferred = $q.defer();
        Restangular.one(hsAPI['checkForceSwitch']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          ids: ids
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      forceSwitch = function(ids) {
        var deferred;
        deferred = $q.defer();
        Restangular.one(hsAPI['forceSwitch']).get({
          accessUser: hsAuth.getAccessKey(),
          accessToken: hsAuth.getAccessToken(),
          ids: ids
        }).then(function(res) {
          if (res.code === '1') {
            deferred.resolve(res.data);
            return mdToastService.showToast(res.message);
          } else {
            deferred.reject(res);
            return mdToastService.showToast(res.message);
          }
        }, function(res) {
          deferred.reject(res);
          return mdToastService.showToast('服务器内部出错');
        });
        return deferred.promise;
      };
      batch = [
        {
          field: 'batchCode',
          name: 'batchCode',
          headerCellFilter: 'translate',
          displayName: '批次号',
          minWidth: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          field: 'id',
          name: 'id',
          headerCellFilter: 'translate',
          displayName: '业务系统ID',
          minWidth: 250,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'batchStatus',
          headerCellClass: 'background',
          headerCellFilter: 'translate',
          displayName: '状态',
          width: 100,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-status.html'
        }, {
          name: 'packageAiuStartDate',
          headerCellFilter: 'translate',
          displayName: '起始时间',
          minWidth: 150,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-startDate.html'
        }, {
          name: 'packageAipEndDate',
          headerCellFilter: 'translate',
          displayName: '结束时间',
          minWidth: 150,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-endDate.html'
        }, {
          field: 'packageCount',
          name: 'packageCount',
          headerCellFilter: 'translate',
          displayName: '数据包数量',
          minWidth: 60,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          field: 'aipCount',
          name: 'aipCount',
          headerCellFilter: 'translate',
          displayName: '数据量',
          minWidth: 60,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'operation',
          enableSorting: false,
          headerCellFilter: 'translate',
          displayName: '',
          minWidth: 100,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-operation.html'
        }
      ];
      batchErrorList = [
        {
          name: 'batchCode',
          headerCellFilter: 'translate',
          displayName: '批次号',
          minWidth: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'id',
          headerCellFilter: 'translate',
          displayName: '业务系统ID',
          minWidth: 250,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'recordName',
          headerCellFilter: 'translate',
          displayName: '申报名称',
          width: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'exceptionDesc',
          headerCellFilter: 'translate',
          displayName: '异常说明',
          minWidth: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'exceptionHandleBehavior',
          headerCellFilter: 'translate',
          displayName: '异常处理',
          minWidth: 60,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-exceptionHandleBehavior.html'
        }, {
          name: 'dealAction',
          headerCellFilter: 'translate',
          displayName: '处理动作',
          minWidth: 60,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-dealAction.html'
        }
      ];
      packageList = [
        {
          name: 'archivalId',
          headerCellFilter: 'translate',
          displayName: '档号',
          minWidth: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'batchCode',
          headerCellFilter: 'translate',
          displayName: '批次号',
          minWidth: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'businessCode',
          headerCellFilter: 'translate',
          displayName: '业务流水号',
          width: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'name',
          headerCellFilter: 'translate',
          displayName: '事项名称',
          minWidth: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'recordCode',
          headerCellFilter: 'translate',
          displayName: '证照编号',
          minWidth: 200,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'createDate',
          headerCellFilter: 'translate',
          displayName: '创建时间',
          minWidth: 150,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-packageList-createDate.html'
        }, {
          name: 'modifyDate',
          headerCellFilter: 'translate',
          displayName: '修改时间',
          minWidth: 150,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-packageList-modifyDate.html'
        }
      ];
      this.forceSwitch = forceSwitch;
      this.checkForceSwitch = checkForceSwitch;
      this.deleteBatch = deleteBatch;
      this.getPackageList = getPackageList;
      this.exportList = exportList;
      this.getErrorList = getErrorList;
      this.getDetailInfo = getDetailInfo;
      this.getErrorGridData = getErrorGridData;
      this.getGridData = getGridData;
      this.batchErrorList = batchErrorList;
      this.packageList = packageList;
      this.batch = batch;
    }
  ]);

}).call(this);

//# sourceMappingURL=batch.service.js.map
