// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").service("batchService", [
    '$log', '$q', '$timeout', '$mdToast', 'hsAuth', 'Restangular', 'hsAPI', 'hsTpl', function($log, $q, $timeout, $mdToast, hsAuth, Restangular, hsAPI, hsTpl) {
      var batch, getDataType, getGridData, getSystemSource, getUnit;
      getSystemSource = function() {
        var deferred, res;
        deferred = $q.defer();
        res = {};
        res.data = ['系统1', '系统2', '系统3', '系统4'];
        return $timeout(function() {
          deferred.resolve(res);
          return deferred.promise;
        }, 1000);
      };
      getUnit = function() {
        var deferred, res;
        deferred = $q.defer();
        res = {};
        res.data = ['单位1', '单位2', '单位3', '单位4'];
        return $timeout(function() {
          deferred.resolve(res);
          return deferred.promise;
        }, 1000);
      };
      getDataType = function() {
        var deferred, res;
        deferred = $q.defer();
        res = {};
        res.data = ['数据1', '数据2', '数据3', '数据4'];
        return $timeout(function() {
          deferred.resolve(res);
          return deferred.promise;
        }, 1000);
      };
      getGridData = function() {
        var arry, deferred, res;
        deferred = $q.defer();
        res = {};
        res.data = [
          {
            objectId: '1',
            status: true,
            startData: '2016-11-21',
            endData: '2016-11-21',
            YWID: 'YW00120170123123455001',
            YWSyetemId: 'YW001',
            YWUnit: '浙江省住建厅',
            AIUAmount: 3789,
            dataAmount: '68.3M',
            keepTime: '1m31s',
            AIPswitch: 3789,
            dataError: 0,
            forceSwitch: 0
          }, {
            objectId: '2',
            status: false,
            startData: '2016-1-21',
            endData: '2016-6-21',
            YWID: 'YW00120171123223455221',
            YWSyetemId: 'YW002',
            YWUnit: '浙江省住建厅',
            AIUAmount: 3789,
            dataAmount: '7.3M',
            keepTime: '29s',
            AIPswitch: 766,
            dataError: 1,
            forceSwitch: 2
          }, {
            objectId: '3',
            status: true,
            startData: '2016-1-21',
            endData: '2016-6-21',
            YWID: 'YW00120171124413455221',
            YWSyetemId: 'YW001',
            YWUnit: '浙江省住建厅',
            AIUAmount: 1344,
            dataAmount: '22.3M',
            keepTime: '1m9s',
            AIPswitch: 122,
            dataError: 1,
            forceSwitch: 2
          }
        ];
        arry = [
          {
            objectId: '1',
            status: true,
            startData: '2016-11-21',
            endData: '2016-11-21',
            YWID: 'YW00120170123123455001',
            YWSyetemId: 'YW001',
            YWUnit: '浙江省住建厅',
            AIUAmount: 3789,
            dataAmount: '68.3M',
            keepTime: '1m31s',
            AIPswitch: 3789,
            dataError: 0,
            forceSwitch: 0
          }, {
            objectId: '2',
            status: false,
            startData: '2016-1-21',
            endData: '2016-6-21',
            YWID: 'YW00120171123223455221',
            YWSyetemId: 'YW002',
            YWUnit: '浙江省住建厅',
            AIUAmount: 3789,
            dataAmount: '7.3M',
            keepTime: '29s',
            AIPswitch: 766,
            dataError: 1,
            forceSwitch: 2
          }, {
            objectId: '3',
            status: true,
            startData: '2016-1-21',
            endData: '2016-6-21',
            YWID: 'YW00120171124413455221',
            YWSyetemId: 'YW001',
            YWUnit: '浙江省住建厅',
            AIUAmount: 1344,
            dataAmount: '22.3M',
            keepTime: '1m9s',
            AIPswitch: 122,
            dataError: 1,
            forceSwitch: 2
          }
        ];
        $timeout(function() {
          return deferred.resolve(res);
        }, 1000);
        return deferred.promise;
      };
      batch = [
        {
          name: 'YWID',
          headerCellFilter: 'translate',
          displayName: '批次号',
          minWidth: 200,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-YW.html'
        }, {
          name: 'YWSyetemId',
          headerCellFilter: 'translate',
          displayName: '业务系统ID',
          minWidth: 100,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'status',
          headerCellClass: 'background',
          headerCellFilter: 'translate',
          displayName: '状态',
          width: 50,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-status.html'
        }, {
          name: 'startData',
          headerCellFilter: 'translate',
          displayName: '时间区间',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'endData',
          headerCellFilter: 'translate',
          displayName: '结束区间',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'AIUAmount',
          headerCellFilter: 'translate',
          displayName: '数据包数量',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'dataAmount',
          headerCellFilter: 'translate',
          displayName: '数据量',
          minWidth: 50,
          cellTemplate: hsTpl.hsCellTemplate
        }, {
          name: 'operation',
          headerCellFilter: 'translate',
          displayName: '',
          minWidth: 150,
          cellTemplate: 'modules/batch/template/ui-grid-template/grid-dataError-operation.html'
        }
      ];
      this.batch = batch;
      this.getGridData = getGridData;
      this.getDataType = getDataType;
      this.getUnit = getUnit;
      this.getSystemSource = getSystemSource;
    }
  ]);

}).call(this);

//# sourceMappingURL=batch.service.js.map
