// Generated by CoffeeScript 1.9.1
(function() {
  angular.module("myApp").service("hsAPI", function() {
    this["userLogin"] = "/user/login";
    this["userLogout"] = "/user/logout";
    this["categoryTree"] = "/category/tree";
    this["test"] = "/erms/import";
  });

}).call(this);

//# sourceMappingURL=hsApi.js.map
