// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module("myApp").service("commonMethodSerivce", [
    '$log', function($log) {
      var includeInArr, initColumn, isArrRepeat, randomNum, randomString, sortArrBy, stringGetLength;
      isArrRepeat = function(arr) {
        var counts, i, item, len, out;
        len = arr.length;
        out = [];
        counts = {};
        i = 0;
        while (i < len) {
          item = arr[i];
          counts[item] = counts[item] >= 1 ? counts[item] + 1 : 1;
          if (counts[item] === 2) {
            out.push(item);
          }
          i++;
        }
        return out.length === 0;
      };
      includeInArr = function(element, arr) {
        var i, j, len1, rows;
        for (i = j = 0, len1 = arr.length; j < len1; i = ++j) {
          rows = arr[i];
          if (arr[i] === element) {
            return true;
          }
        }
        return false;
      };
      initColumn = function(name, predicate, type, value) {
        return {
          name: name,
          predicate: predicate,
          type: type,
          value: value
        };
      };
      sortArrBy = function(name) {
        return function(o, p) {
          var a, b;
          a = void 0;
          b = void 0;
          if (typeof o === 'object' && typeof p === 'object' && o && p) {
            a = o[name];
            b = p[name];
            if (a === b) {
              return 0;
            }
            if (typeof a === typeof b) {
              if (a < b) {
                return -1;
              } else {
                return 1;
              }
            }
            if (typeof a < typeof b) {
              return -1;
            } else {
              return 1;
            }
          } else {
            throw 'error';
          }
        };
      };
      randomString = function(len) {
        var $chars, i, maxPos, pwd;
        len = len || 32;
        $chars = 'ABCDEFGHJKMNPQRSTWXYZabcdefhijkmnprstwxyz2345678';

        /****默认去掉了容易混淆的字符oOLl,9gq,Vv,Uu,I1*** */
        maxPos = $chars.length;
        pwd = '';
        i = 0;
        while (i < len) {
          pwd += $chars.charAt(Math.floor(Math.random() * maxPos));
          i++;
        }
        return pwd;
      };
      randomNum = function(len) {
        var i, num;
        len = len || 32;
        num = '';
        i = 0;
        while (i < len) {
          num += Math.floor(Math.random() * 10);
          i++;
        }
        return num;
      };
      stringGetLength = function(str) {
        var charCode, i, len, realLength;
        realLength = 0;
        len = str.length;
        charCode = -1;
        i = 0;
        while (i < len) {
          charCode = str.charCodeAt(i);
          if (charCode >= 0 && charCode <= 128) {
            realLength++;
          } else {
            realLength = realLength + 2;
          }
          i++;
        }
        return realLength;
      };
      this.stringGetLength = stringGetLength;
      this.randomNum = randomNum;
      this.randomString = randomString;
      this.sortArrBy = sortArrBy;
      this.initColumn = initColumn;
      this.includeInArr = includeInArr;
      this.isArrRepeat = isArrRepeat;
    }
  ]);

}).call(this);

//# sourceMappingURL=commonMethod.service.js.map
